<?php die();

/**

 * Add you custom models here that you are loading in your controllers

 *

 * <code>

 * $this->site_model->get_records()

 * </code>

 * Where site_model is the model Class

 *

 * ---------------------- Models to Load ----------------------

 * <examples>

 *

* @property agent_control $agent_control
* @property available_time $available_time
* @property ban_investor $ban_investor
* @property base32 $base32
* @property category_expression $category_expression
* @property chinese_pinyin $chinese_pinyin
* @property crm $crm
* @property curl $curl
* @property ic_mail $ic_mail
* @property imap_mailbox $imap_mailbox
* @property ir_library $ir_library
* @property ivr_interface $ivr_interface
* @property language $language
* @property maimai_api $maimai_api
* @property ocscache $ocscache
* @property autoloader $autoloader
* @property apc $apc
* @property cachebase $cachebase
* @property discisam $discisam
* @property icache $icache
* @property igbinary $igbinary
* @property memcache $memcache
* @property memory $memory
* @property memorygzip $memorygzip
* @property memoryserialized $memoryserialized
* @property phptemp $phptemp
* @property sqlite $sqlite
* @property sqlite3 $sqlite3
* @property wincache $wincache
* @property cachedobjectstoragefactory $cachedobjectstoragefactory
* @property cyclicreferencestack $cyclicreferencestack
* @property logger $logger
* @property database $database
* @property datetime $datetime
* @property engineering $engineering
* @property exception $exception
* @property exceptionhandler $exceptionhandler
* @property financial $financial
* @property formulaparser $formulaparser
* @property formulatoken $formulatoken
* @property function $function
* @property functions $functions
* @property logical $logical
* @property lookupref $lookupref
* @property mathtrig $mathtrig
* @property statistical $statistical
* @property textdata $textdata
* @property stack $stack
* @property calculation $calculation
* @property advancedvaluebinder $advancedvaluebinder
* @property datatype $datatype
* @property datavalidation $datavalidation
* @property defaultvaluebinder $defaultvaluebinder
* @property hyperlink $hyperlink
* @property ivaluebinder $ivaluebinder
* @property cell $cell
* @property dataseries $dataseries
* @property dataseriesvalues $dataseriesvalues
* @property layout $layout
* @property legend $legend
* @property plotarea $plotarea
* @property jpgraph $jpgraph
* @property title $title
* @property chart $chart
* @property comment $comment
* @property documentproperties $documentproperties
* @property documentsecurity $documentsecurity
* @property hashtable $hashtable
* @property icomparable $icomparable
* @property iofactory $iofactory
* @property namedrange $namedrange
* @property abstract $abstract
* @property csv $csv
* @property defaultreadfilter $defaultreadfilter
* @property excel2003xml $excel2003xml
* @property theme $theme
* @property excel2007 $excel2007
* @property escher $escher
* @property excel5 $excel5
* @property gnumeric $gnumeric
* @property html $html
* @property ireadfilter $ireadfilter
* @property ireader $ireader
* @property oocalc $oocalc
* @property sylk $sylk
* @property referencehelper $referencehelper
* @property itextelement $itextelement
* @property run $run
* @property textelement $textelement
* @property richtext $richtext
* @property settings $settings
* @property codepage $codepage
* @property date $date
* @property drawing $drawing
* @property spcontainer $spcontainer
* @property spgrcontainer $spgrcontainer
* @property dgcontainer $dgcontainer
* @property blip $blip
* @property bse $bse
* @property bstorecontainer $bstorecontainer
* @property dggcontainer $dggcontainer
* @property file $file
* @property font $font
* @property choleskydecomposition $choleskydecomposition
* @property eigenvaluedecomposition $eigenvaluedecomposition
* @property ludecomposition $ludecomposition
* @property matrix $matrix
* @property qrdecomposition $qrdecomposition
* @property singularvaluedecomposition $singularvaluedecomposition
* @property error $error
* @property maths $maths
* @property chainedblockstream $chainedblockstream
* @property root $root
* @property pps $pps
* @property ole $ole
* @property oleread $oleread
* @property pclzip.lib $pclzip.lib
* @property passwordhasher $passwordhasher
* @property string $string
* @property timezone $timezone
* @property xmlwriter $xmlwriter
* @property ziparchive $ziparchive
* @property zipstreamwrapper $zipstreamwrapper
* @property bestfitclass $bestfitclass
* @property exponentialbestfitclass $exponentialbestfitclass
* @property linearbestfitclass $linearbestfitclass
* @property logarithmicbestfitclass $logarithmicbestfitclass
* @property polynomialbestfitclass $polynomialbestfitclass
* @property powerbestfitclass $powerbestfitclass
* @property trendclass $trendclass
* @property alignment $alignment
* @property border $border
* @property borders $borders
* @property color $color
* @property conditional $conditional
* @property fill $fill
* @property numberformat $numberformat
* @property protection $protection
* @property supervisor $supervisor
* @property style $style
* @property rule $rule
* @property column $column
* @property autofilter $autofilter
* @property basedrawing $basedrawing
* @property celliterator $celliterator
* @property columndimension $columndimension
* @property shadow $shadow
* @property headerfooter $headerfooter
* @property headerfooterdrawing $headerfooterdrawing
* @property memorydrawing $memorydrawing
* @property pagemargins $pagemargins
* @property pagesetup $pagesetup
* @property row $row
* @property rowdimension $rowdimension
* @property rowiterator $rowiterator
* @property sheetview $sheetview
* @property worksheet $worksheet
* @property worksheetiterator $worksheetiterator
* @property comments $comments
* @property contenttypes $contenttypes
* @property docprops $docprops
* @property rels $rels
* @property stringtable $stringtable
* @property workbook $workbook
* @property writerpart $writerpart
* @property biffwriter $biffwriter
* @property parser $parser
* @property xf $xf
* @property iwriter $iwriter
* @property core $core
* @property dompdf $dompdf
* @property mpdf $mpdf
* @property tcpdf $tcpdf
* @property pdf $pdf
* @property phpexcel $phpexcel
* @property project_category $project_category
* @property project_hand $project_hand
* @property project_icon $project_icon
* @property project_shuffle $project_shuffle
* @property project_util $project_util
* @property risk_control $risk_control
* @property role_control $role_control
* @property schedule_format $schedule_format
* @property search_library $search_library
* @property session $session
* @property sms_interface $sms_interface
* @property stat_kpi_item $stat_kpi_item
* @property statistic $statistic
* @property upload_file $upload_file
* @property user_message $user_message
* @property user_task $user_task
* @property wiki_library $wiki_library
* @property xcache $xcache
* @property xstorage $xstorage
* @property securimage $securimage
* @property filterascii85 $filterascii85
* @property filterasciihexdecode $filterasciihexdecode
* @property filterlzw $filterlzw
* @property fpdf_tpl $fpdf_tpl
* @property fpdi $fpdi
* @property fpdi_bridge $fpdi_bridge
* @property fpdi_pdf_parser $fpdi_pdf_parser
* @property pdf_context $pdf_context
* @property pdf_parser $pdf_parser
* @property qrcode $qrcode
* @property index $index
* @property phpqrcode $phpqrcode
* @property qrbitstream $qrbitstream
* @property qrconfig $qrconfig
* @property qrconst $qrconst
* @property qrencode $qrencode
* @property qrimage $qrimage
* @property qrinput $qrinput
* @property qrlib $qrlib
* @property qrmask $qrmask
* @property qrrscode $qrrscode
* @property qrspec $qrspec
* @property qrsplit $qrsplit
* @property qrtools $qrtools
* @property broker $broker
* @property notattachedexception $notattachedexception
* @property server $server
* @property abstractadapter $abstractadapter
* @property adapterinterface $adapterinterface
* @property apcu $apcu
* @property memcached $memcached
* @property mongo $mongo
* @property mysqli $mysqli
* @property notcache $notcache
* @property predis $predis
* @property cache $cache
* @property cacheinterface $cacheinterface
* @property adapternotsetexception $adapternotsetexception
* @property cacheexception $cacheexception
* @property abstractcachetest $abstractcachetest
* @property apcucachetest $apcucachetest
* @property filetest $filetest
* @property memcachetest $memcachetest
* @property memcachedtest $memcachedtest
* @property memorytest $memorytest
* @property mongotest $mongotest
* @property mysqlitest $mysqlitest
* @property notcachetest $notcachetest
* @property predistest $predistest
* @property cachetest $cachetest
* @property bootstrap $bootstrap
* @property nocache $nocache
* @property common $common
* @property tcpdf_autoconfig $tcpdf_autoconfig
* @property tcpdf_barcodes_1d $tcpdf_barcodes_1d
* @property tcpdf_barcodes_2d $tcpdf_barcodes_2d
* @property tcpdf_import $tcpdf_import
* @property tcpdf_parser $tcpdf_parser
* @property wx_interface $wx_interface
* @property wx_menu $wx_menu
* @property wx_message $wx_message
* @property advertise_flow_model $advertise_flow_model
* @property agent_coin_model $agent_coin_model
* @property agent_coin_operation_model $agent_coin_operation_model
* @property agent_info_model $agent_info_model
* @property agent_project_lottery_model $agent_project_lottery_model
* @property agent_score_model $agent_score_model
* @property agent_score_operation_model $agent_score_operation_model
* @property agent_sector_model $agent_sector_model
* @property app_feedback_model $app_feedback_model
* @property app_patch_model $app_patch_model
* @property banner_message_model $banner_message_model
* @property bp_haitou_model $bp_haitou_model
* @property category_attribute_model $category_attribute_model
* @property category_backend_model $category_backend_model
* @property category_frontend_model $category_frontend_model
* @property category_recommend_model $category_recommend_model
* @property code_distribute_model $code_distribute_model
* @property code_distribute_task_model $code_distribute_task_model
* @property contacts_model $contacts_model
* @property cookie_tracker_model $cookie_tracker_model
* @property dev_req_model $dev_req_model
* @property email_inbox_model $email_inbox_model
* @property email_model $email_model
* @property email_tracker_model $email_tracker_model
* @property experimental_event_data_model $experimental_event_data_model
* @property feedback_model $feedback_model
* @property feeds_model $feeds_model
* @property field_flow_model $field_flow_model
* @property fund_model $fund_model
* @property fund_sector_model $fund_sector_model
* @property galary_model $galary_model
* @property gift_model $gift_model
* @property hand_risk_log_model $hand_risk_log_model
* @property home_model $home_model
* @property http_request_log_model $http_request_log_model
* @property ic_model $ic_model
* @property investor_action_model $investor_action_model
* @property investor_app_log_model $investor_app_log_model
* @property investor_app_not_verified_log_model $investor_app_not_verified_log_model
* @property investor_banlist_model $investor_banlist_model
* @property investor_case_model $investor_case_model
* @property investor_date_history $investor_date_history
* @property investor_filter_model $investor_filter_model
* @property investor_focus_agent_list_model $investor_focus_agent_list_model
* @property investor_info_model $investor_info_model
* @property investor_offline_log_model $investor_offline_log_model
* @property investor_privilege_model $investor_privilege_model
* @property investor_project_cursor_model $investor_project_cursor_model
* @property investor_project_list_model $investor_project_list_model
* @property investor_project_prefecture_model $investor_project_prefecture_model
* @property investor_rss_log_model $investor_rss_log_model
* @property investor_rss_model $investor_rss_model
* @property investor_stats_model $investor_stats_model
* @property kpi_model $kpi_model
* @property launch_screen_model $launch_screen_model
* @property leads_custom_filter_model $leads_custom_filter_model
* @property log_model $log_model
* @property meeting_feedback_agent_model $meeting_feedback_agent_model
* @property meeting_feedback_founder_model $meeting_feedback_founder_model
* @property meeting_feedback_investor_model $meeting_feedback_investor_model
* @property meeting_followup_model $meeting_followup_model
* @property meeting_log_model $meeting_log_model
* @property meeting_model $meeting_model
* @property meeting_ticket_model $meeting_ticket_model
* @property outer_agent_info_model $outer_agent_info_model
* @property performance_log_model $performance_log_model
* @property personalized_blacklist_model $personalized_blacklist_model
* @property platform_data_model $platform_data_model
* @property playground_def_model $playground_def_model
* @property privilege_model $privilege_model
* @property privilege_role_model $privilege_role_model
* @property privilege_role_relation_model $privilege_role_relation_model
* @property privilege_rule_model $privilege_rule_model
* @property privilege_user_model $privilege_user_model
* @property privilege_user_rule_model $privilege_user_rule_model
* @property project_agent_barcode_model $project_agent_barcode_model
* @property project_agent_event_model $project_agent_event_model
* @property project_agent_status_model $project_agent_status_model
* @property project_agent_subevent_model $project_agent_subevent_model
* @property project_attach_image_model $project_attach_image_model
* @property project_category_backend_model $project_category_backend_model
* @property project_category_frontend_model $project_category_frontend_model
* @property project_closing_info_model $project_closing_info_model
* @property project_endorse_model $project_endorse_model
* @property project_event_model $project_event_model
* @property project_fridge_model $project_fridge_model
* @property project_globle_search_model $project_globle_search_model
* @property project_investment_model $project_investment_model
* @property project_investor_closing_info_model $project_investor_closing_info_model
* @property project_investor_event_model $project_investor_event_model
* @property project_investor_status_model $project_investor_status_model
* @property project_leads_comment_model $project_leads_comment_model
* @property project_leads_model $project_leads_model
* @property project_leads_operation_model $project_leads_operation_model
* @property base_investment_model $base_investment_model
* @property base_project_model $base_project_model
* @property base_project_team_model $base_project_team_model
* @property project_operation_log_model $project_operation_log_model
* @property project_maimai_info_model $project_maimai_info_model
* @property project_model $project_model
* @property project_operation_model $project_operation_model
* @property project_private_sea_model $project_private_sea_model
* @property project_recommend_model $project_recommend_model
* @property project_related_investor_model $project_related_investor_model
* @property project_set_model $project_set_model
* @property project_share_log_model $project_share_log_model
* @property project_share_model $project_share_model
* @property project_snapshot_log_model $project_snapshot_log_model
* @property project_stage_model $project_stage_model
* @property project_stats_model $project_stats_model
* @property project_status_log_model $project_status_log_model
* @property project_term_sheet_investor_model $project_term_sheet_investor_model
* @property project_term_sheet_model $project_term_sheet_model
* @property project_term_sheet_operation_model $project_term_sheet_operation_model
* @property project_timed_queue_model $project_timed_queue_model
* @property project_type_model $project_type_model
* @property project_visiblity_model $project_visiblity_model
* @property project_xuetang_info_model $project_xuetang_info_model
* @property push_app_icon_number_model $push_app_icon_number_model
* @property push_recommend_project_model $push_recommend_project_model
* @property push_task_model $push_task_model
* @property redirect_model $redirect_model
* @property region_model $region_model
* @property resource_map_model $resource_map_model
* @property response_log_model $response_log_model
* @property search_query_hot_model $search_query_hot_model
* @property search_query_log_model $search_query_log_model
* @property verified_user_model $verified_user_model
* @property sending_info_model $sending_info_model
* @property service_monitor_log_model $service_monitor_log_model
* @property sms_backup_list_model $sms_backup_list_model
* @property sms_task_model $sms_task_model
* @property sms_verify_code_model $sms_verify_code_model
* @property db_push_list_model $db_push_list_model
* @property db_push_task_model $db_push_task_model
* @property sql_exec_history_model $sql_exec_history_model
* @property sql_model $sql_model
* @property sql_privilege_model $sql_privilege_model
* @property sql_update_model $sql_update_model
* @property staff_group_model $staff_group_model
* @property staff_info_model $staff_info_model
* @property action_source_stats_model $action_source_stats_model
* @property token_model $token_model
* @property top_project_model $top_project_model
* @property user_available_time_model $user_available_time_model
* @property user_coldcall_model $user_coldcall_model
* @property user_comment_model $user_comment_model
* @property user_feedback_founder_model $user_feedback_founder_model
* @property user_feedback_model $user_feedback_model
* @property user_im_group_member_model $user_im_group_member_model
* @property user_im_group_model $user_im_group_model
* @property user_im_message_model $user_im_message_model
* @property user_im_message_received_model $user_im_message_received_model
* @property user_im_project_group_model $user_im_project_group_model
* @property user_label_model $user_label_model
* @property user_maimai_info_model $user_maimai_info_model
* @property user_message_model $user_message_model
* @property user_model $user_model
* @property user_notice_confirm_model $user_notice_confirm_model
* @property user_privilege_config_model $user_privilege_config_model
* @property user_process_log_model $user_process_log_model
* @property user_project_event_model $user_project_event_model
* @property user_project_relation_model $user_project_relation_model
* @property user_schedule_model $user_schedule_model
* @property user_sector_model $user_sector_model
* @property user_shared_data_model $user_shared_data_model
* @property user_subscribe_model $user_subscribe_model
* @property user_task_model $user_task_model
* @property user_xuetang_comment_model $user_xuetang_comment_model
* @property validation_model $validation_model
* @property vc_log_model $vc_log_model
* @property vc_response_log_model $vc_response_log_model
* @property waiting_user_model $waiting_user_model
* @property webview_flow_model $webview_flow_model
* @property webview_js_switch_model $webview_js_switch_model
* @property user_weixin_message_model $user_weixin_message_model
* @property user_weixin_model $user_weixin_model
* @property weixin_log_model $weixin_log_model
* @property weixin_model $weixin_model
* @property weixin_staff_code_model $weixin_staff_code_model
* @property weixin_third_party_coupon_model $weixin_third_party_coupon_model
* @property wiki_fund_content_model $wiki_fund_content_model
* @property wiki_investment_diff_model $wiki_investment_diff_model
* @property wiki_investment_model $wiki_investment_model
* @property wiki_investment_shadow_model $wiki_investment_shadow_model
* @property wiki_investor_content_model $wiki_investor_content_model
* @property www_track_model $www_track_model
* @property wx_push_list_model $wx_push_list_model
* @property wx_push_task_model $wx_push_task_model
* @property xuetang_activity_model $xuetang_activity_model
* @property xuetang_user_info_model $xuetang_user_info_model
* @property project_detail $project_detail
* @property admin $admin
* @property target_investor_sync $target_investor_sync
* @property membership_model $membership_model

 *

 *

 *

 */

class my_models

{

}

// End my_models.php
